/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),Module=require("node:module"),ts=require("typescript"),{execFileSync}=require("node:child_process")
const root=path.resolve(__dirname,"..")
require("./cms-load.cjs")
function load(file,replace={}){let src=fs.readFileSync(path.join(root,file),"utf8");for(const[a,b]of Object.entries(replace))src=src.replace(a,b);const code=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const m=new Module(path.join(root,file),module);m.filename=path.join(root,file);m.paths=Module._nodeModulePaths(root);m._compile(code,m.filename);return m.exports}
const core=load("src/lib/cms/engine.ts"),sha=s=>crypto.createHash("sha256").update(s).digest("hex"),text="Indonesia mencatat hasil resmi pada pertandingan final. Penyelenggara mengonfirmasi hasil ini dan menyebut konteks pertandingan."
const packet={version:3,narrative_reviewed:true,context:Object.fromEntries(["who","what","when","where","why","how"].map(k=>[k,"Konteks terverifikasi"])),event_status:"FINAL",event_at:new Date(Date.now()-3600000).toISOString(),assignment:{pillar:"Olahraga Indonesia",angle:"Apresiasi",why_now:"Hasil resmi baru diumumkan penyelenggara pertandingan."},sources:[{id:"p",url:"https://federasi.example/news",publisher_group:"federation",primary:true,published_at:new Date().toISOString(),text,sha256:sha(text)},{id:"s",url:"https://redaksi.example/news",publisher_group:"newsroom",primary:false,published_at:new Date().toISOString(),text,sha256:sha(text)}],claims:[{id:"c",text:"Indonesia mencatat hasil resmi pada pertandingan final.",verified:true,evidence:[{source_id:"p",quote:text},{source_id:"s",quote:text}]}],slides:["hook","fact","chronology","context","closing"].map(role=>({role,headline:"Hasil resmi Indonesia",body:"Konteks pertandingan sudah dikonfirmasi.",claim_ids:["c"]})),media:{url:"https://media.example/photo.jpg",type:"image",credit:"QA",rights_evidence:"Fixture",scope:"QA",rights_status:"CLEARED"}}
const style=load("src/lib/cms/carousel-style.ts")
const writing=load("src/lib/cms/news-writing.ts")
packet.article={version:1,genre:"NEWS",title:"Indonesia Raih Gelar di Final",dek:"Penyelenggara mengonfirmasi kemenangan Indonesia pada pertandingan penutup.",caption:"Indonesia meraih gelar pada pertandingan final setelah hasilnya dikonfirmasi penyelenggara.",benchmark_ids:["qa-news"],paragraphs:[
 {id:"lead",heading:"INDONESIA RAIH GELAR",text:"Indonesia meraih gelar pada pertandingan final. Konfirmasi penyelenggara menjadi dasar laporan hasil pertandingan ini.",claim_ids:["c"],kind:"FACT"},
 {id:"result",heading:"KONFIRMASI PENYELENGGARA",text:"Pengumuman penyelenggara mencantumkan hasil pertandingan penutup kompetisi. Catatan tersebut menjadi rujukan redaksi untuk memastikan identitas pemenang.",claim_ids:["c"],kind:"FACT"},
 {id:"context",heading:"AKHIR PERJALANAN KOMPETISI",text:"Pertandingan final menutup rangkaian kompetisi yang diikuti peserta. Catatan pertandingan membantu pembaca menempatkan kemenangan dalam perjalanan turnamen.",claim_ids:["c"],kind:"FACT"},
 {id:"report",heading:"CATATAN PERTANDINGAN FINAL",text:"Laporan pertandingan mencatat penampilan Indonesia di partai penutup. Hasil tersebut diumumkan setelah pertandingan selesai, dengan pengumuman resmi sebagai rujukan.",claim_ids:["c"],kind:"FACT"}
],review:{reviewer_id:"QA",reviewed_at:new Date().toISOString(),article_digest:""}};
packet.article.review.article_digest=writing.articleDigest(packet.article);packet.slides=writing.articleSlides(packet.article)
packet.media.editorial_cover={url:"https://media.example/cover.png",sha256:"0".repeat(64),style_version:style.CAROUSEL_STYLE,source_photo_url:packet.media.url,headline:packet.slides[0].headline,dek:packet.slides[0].body,source_label:"FEDERASI.EXAMPLE",reviewed_at:new Date().toISOString(),reviewed_by:"QA",safe_wrap:true,authentic_subject:true,editorial_background:true,no_edition_label:true,no_promotional_footer:true}
packet.media.editorial_cover.page_count=packet.slides.length
assert.deepEqual(core.auditPacket(packet,"CAROUSEL"),[])
const reverse=v=>Array.isArray(v)?v.map(reverse):v&&typeof v==="object"?Object.fromEntries(Object.entries(v).reverse().map(([k,x])=>[k,reverse(x)])):v;assert.equal(core.packetDigest(packet),core.packetDigest(reverse(packet)));assert.notEqual(core.packetDigest(packet),core.packetDigest({...packet,event_status:"LIVE"}));
const change=f=>{const p=structuredClone(packet);f(p);return core.auditPacket(p,"CAROUSEL")}
assert(change(p=>p.sources.pop()).length);assert(change(p=>p.sources[1].publisher_group="federation").some(x=>x.includes("kelompok")));assert(change(p=>p.claims[0].evidence[1].quote="Tidak cocok").length);assert(change(p=>p.media.rights_status="PENDING").some(x=>x.includes("Feed")))
assert(core.auditPacket(packet,"REEL").some(x=>x.includes("video nyata")))
const item={title:"Hasil resmi Indonesia",caption:"Fakta hasil final.",format:"CAROUSEL",assets:packet.slides.map(()=>({url:"https://media.example/x.jpg"})),editorial_meta:{standard:core.ENGINE,engine_packet:packet,engine_state:"READY_FOR_REVIEW",rendered_packet_digest:core.packetDigest(packet),render_audit:{ok:true}}}
assert(core.enginePublicationIssues(item,false).some(x=>x.includes("gaya koran")))
assert(core.enginePublicationIssues({...item,editorial_meta:{standard:"LEGACY"}},false).some(x=>x.includes("legacy")))
assert(change(p=>delete p.media.editorial_cover).some(x=>x.includes("kolase")))
assert(change(p=>p.slides[0].headline="Judul lain").some(x=>x.includes("Cover editorial")))
;(async()=>{
 const sharp=require("sharp");global.__photo=await sharp({create:{width:1080,height:1350,channels:3,background:"#6a8490"}}).jpeg().toBuffer();packet.media.editorial_cover.sha256=sha(global.__photo)
 const media=load("src/lib/cms/engine-media.ts",{"await sourceBytes(cover.url)":"global.__photo","await sourceBytes(String(asset.url || asset.image_url || \"\"))":"global.__testAssetBytes","await sourceBytes(clip.media_url, 150_000_000)":"global.__video"})
 const carousel=await media.renderCarousel(packet);assert.equal(carousel.length,5);assert(carousel[0].audit.authentic_photo);assert(carousel.every(x=>x.audit.safe_wrap));assert.equal(carousel[0].audit.source_label,"FEDERASI.EXAMPLE");assert(carousel.slice(1).every(x=>x.audit.source_label===null));const full=structuredClone(packet);full.article.paragraphs[0].text+=" Para pemain menyelesaikan rangkaian pertandingan dengan kerja bersama di lapangan. Pendukung mengikuti partai penutup hingga hasilnya diumumkan. Panitia menyiapkan laporan yang memuat identitas peserta. Perjalanan kompetisi berakhir setelah pertandingan final. Pengumuman menjadi rujukan pencatatan hasil untuk para peserta.";full.article.review.article_digest=writing.articleDigest(full.article);full.slides=writing.articleSlides(full.article);assert.deepEqual(core.auditPacket(full,"CAROUSEL"),[]);const dense=await media.renderCarousel(full);assert(dense[1].audit.body_font_size>=32);const overflow=structuredClone(packet);overflow.slides[1].body=Array(100).fill("Artikel sangat panjang perlu dibagi menjadi halaman berikutnya.").join(" ");await assert.rejects(()=>media.renderCarousel(overflow),/Slide berbeda/);await assert.rejects(()=>media.measuredText(overflow.slides[1].body,936,800,36),/Teks melampaui/);for(const r of carousel){const m=await sharp(r.bytes).metadata();assert.equal(m.width,1080);assert.equal(m.height,1350)}
 item.assets=carousel.map((r)=>({url:"https://media.example/x.jpg",render_audit:r.audit}));item.editorial_meta.rendered_packet_digest=core.packetDigest(packet);item.editorial_meta.engine_approval={actor_id:"editor",digest:core.contentDigest(item)};assert.deepEqual(core.enginePublicationIssues(item),[]);assert.equal(core.contentDigest(item),core.contentDigest(reverse(item)));item.caption+=" berubah";assert(core.enginePublicationIssues(item).some(x=>x.includes("Editor")))
 assert(carousel.every(r=>r.audit.style_version===style.CAROUSEL_STYLE));assert.equal(carousel[0].audit.layout,"newspaper_collage_cover")
 const mutated=structuredClone(packet);mutated.media.editorial_cover.sha256="1".repeat(64);await assert.rejects(()=>media.renderCarousel(mutated),/Berkas cover berubah/)
 const unaudited=structuredClone(item.assets);unaudited[0].render_audit.layout="newspaper_photo";assert(style.carouselStyleIssues(unaudited).length)
 global.__testAssetBytes=carousel[0].bytes;const bound=item.assets.map((a)=>({...a,render_audit:{...a.render_audit,output_sha256:sha(global.__testAssetBytes)}}));await media.verifyCarouselAssets(bound)
 global.__testAssetBytes=Buffer.concat([carousel[0].bytes,Buffer.from("changed")]);await assert.rejects(()=>media.verifyCarouselAssets(bound),/berubah setelah render/)
 global.__photo=await sharp({create:{width:1080,height:1080,channels:3,background:"#6a8490"}}).jpeg().toBuffer();const square=structuredClone(packet);square.media.editorial_cover.sha256=sha(global.__photo);await assert.rejects(()=>media.renderCarousel(square),/rasio 4:5/)
 const dir=fs.mkdtempSync("/tmp/stadione-montage-qa-"),source=path.join(dir,"fixture.mp4")
 try{
  execFileSync("ffmpeg",["-v","error","-y","-f","lavfi","-i","testsrc2=size=640x360:rate=30","-f","lavfi","-i","sine=frequency=440:sample_rate=48000","-t","9","-c:v","libx264","-pix_fmt","yuv420p","-c:a","aac",source],{timeout:30000});global.__video=fs.readFileSync(source)
  const clip=(id,platform)=>({id,platform,page_url:`https://${platform.toLowerCase()}.example/watch/${id}`,media_url:`https://cdn.example/${id}.mp4`,creator:`Creator ${id}`,published_at:new Date().toISOString(),transcript:"Transkrip sumber nyata yang cukup panjang untuk pengujian montage berita olahraga.",credit:`Creator ${id} / ${platform}`,rights_status:"LICENSED",rights_evidence:"QA synthetic license",scope:"Social editorial",audio_rights:"CLEARED"})
  packet.media={...packet.media,type:"video",article_image:{url:"https://media.example/frame.jpg",credit:"QA real source frame"},video_sources:[clip("yt","YOUTUBE"),clip("tt","TIKTOK")],scenes:[{source_id:"yt",source_start:0,source_end:3,text:"Aksi utama",claim_ids:["c"]},{source_id:"tt",source_start:0,source_end:3,text:"Reaksi pemain",claim_ids:["c"]},{source_id:"yt",source_start:3,source_end:6,text:"Konteks hasil",claim_ids:["c"]}]}
  assert.deepEqual(core.auditPacket(packet,"REEL"),[])
  const noHero=structuredClone(packet);delete noHero.media.article_image;assert(core.auditPacket(noHero,"REEL").some(x=>x.includes("frame asli")))
  const reel=await media.renderReel(packet);assert(reel.audit.ok);assert.equal(reel.audit.source_count,2);assert.equal(reel.audit.ai_footage,false);assert.equal(reel.audit.height,1920);assert(reel.audit.duration>=8)
  packet.media.scenes[2].source_end=20;await assert.rejects(()=>media.renderReel(packet),/melewati durasi/)
 }finally{fs.rmSync(dir,{recursive:true,force:true})}
 console.log(JSON.stringify({ok:true,tests:["claim_ledger","feed_rights","approval_digest","locked_collage_cover","no_raw_photo_fallback","legacy_style_blocked","cover_source_and_text_binding","cover_checksum","asset_checksum_before_meta","no_square_cover_crop","full_article_safe_wrap","carousel_1080x1350","multi_source_montage","youtube_tiktok_provenance","scene_timestamp_bounds","changing_captions","credit_overlay","audio_normalization","reel_1080x1920","no_ai_footage"]}))
})().catch(e=>{console.error(e);process.exitCode=1})
